# Generated by Django 4.0.4 on 2022-05-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('image', models.FileField(default=None, upload_to='img/', verbose_name='Превью')),
                ('link', models.CharField(max_length=180, verbose_name='Ссылка')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
