# Generated by Django 4.0.4 on 2022-05-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_links_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='image',
            field=models.FileField(upload_to='links/img/', verbose_name='Превью'),
        ),
    ]
